
import streamlit as st
import pandas as pd
import plotly.express as px
import numpy as np

from calculation import (
    aerodynamic_forces,
    stall_speed,
    estimated_wing_root_stress,
)
from validation import validate_inputs, validate_result, data_status


st.set_page_config(
    page_title="AeroLab Dashboard",
    page_icon="✈️",
    layout="wide",
)

st.title("✈️ AeroLab")
st.subheader("Aerodynamic Testing & Analysis")
st.caption("Low-cost wind-tunnel concept | Simulation prototype")

st.warning(
    "SIMULATION MODE: Results are generated by a simplified "
    "mathematical model. They are not physical wind-tunnel "
    "measurements or validated aircraft-design predictions."
)


# ---------- SIDEBAR CONTROLS ----------
st.sidebar.header("AeroLab Controls")

st.sidebar.subheader("Airflow")
rho = st.sidebar.slider(
    "Air density (kg/m³)", 0.1, 2.0, 1.225, 0.025
)
velocity = st.sidebar.slider(
    "Air velocity (m/s)", 1.0, 50.0, 15.0, 0.5
)

st.sidebar.subheader("Wing / Model")
wing_area = st.sidebar.slider(
    "Wing reference area (m²)", 0.01, 10.0, 0.25, 0.01
)
mass = st.sidebar.slider(
    "Aircraft mass (kg)", 0.1, 1000.0, 1.0, 0.1
)
angle = st.sidebar.slider(
    "Angle of attack (°)", -20.0, 20.0, 5.0, 0.5
)

st.sidebar.subheader("Aerodynamic Model")
cl_max = st.sidebar.slider(
    "Maximum lift coefficient", 0.2, 2.5, 1.2, 0.1
)
stall_angle = st.sidebar.slider(
    "Assumed stall angle (°)", 5.0, 25.0, 14.0, 0.5
)

st.sidebar.subheader("Structural Estimate")
wingspan = st.sidebar.slider(
    "Wing span (m)", 0.05, 20.0, 1.0, 0.05
)
spar_width = st.sidebar.slider(
    "Spar width (m)", 0.001, 1.0, 0.02, 0.001
)
spar_thickness = st.sidebar.slider(
    "Spar thickness (m)", 0.001, 1.0, 0.01, 0.001
)

# ---------------- VALIDATION ----------------
check = validate_inputs(
    rho, velocity, wing_area, mass, angle, cl_max, stall_angle
)

st.markdown("### Data status")
st.info(data_status("simulation"))

if check["errors"]:
    for error in check["errors"]:
        st.error(error)
    st.stop()

for warning in check["warnings"]:
    st.warning(warning)

# ---------------- CURRENT TEST ----------------
current = aerodynamic_forces(
    rho,
    velocity,
    wing_area,
    angle,
    cl_max=cl_max,
    stall_angle_deg=stall_angle,
)

vs = stall_speed(
    mass,
    wing_area,
    rho,
    cl_max=cl_max,
)

stress = estimated_wing_root_stress(
    current["lift_N"],
    wingspan,
    spar_width,
    spar_thickness,
)

result_check = validate_result({
    **current,
    "stall_speed_m_s": vs,
    "estimated_stress_MPa": stress["stress_MPa"],
})

if not result_check["valid"]:
    for error in result_check["errors"]:
        st.error(error)
    st.stop()

# ---------------- KPI CARDS ----------------
st.markdown("### Consolidated results")

c1, c2, c3, c4 = st.columns(4)

c1.metric("Lift", f'{current["lift_N"]:.3f} N')
c2.metric("Drag", f'{current["drag_N"]:.3f} N')
c3.metric("Lift coefficient", f'{current["CL"]:.3f}')
c4.metric("Drag coefficient", f'{current["CD"]:.4f}')

c5, c6, c7 = st.columns(3)

c5.metric("Dynamic pressure", f'{current["dynamic_pressure_pa"]:.2f} Pa')
c6.metric("Idealized stall speed", f"{vs:.2f} m/s")
c7.metric("Estimated spar stress", f'{stress["stress_MPa"]:.3f} MPa')

st.caption(
    "The stress estimate assumes uniform lift distribution and "
    "an ideal rectangular spar. It is not a strength or safety certification."
)

# ---------------- ANGLE SWEEP ----------------
st.markdown("### Aerodynamic response versus angle of attack")

angles = np.arange(-20, 20.5, 0.5)
rows = []

for a in angles:
    r = aerodynamic_forces(
        rho, velocity, wing_area, float(a),
        cl_max=cl_max,
        stall_angle_deg=stall_angle,
    )
    rows.append(r)

curve = pd.DataFrame(rows)

tab1, tab2, tab3 = st.tabs([
    "Lift and drag",
    "Coefficient curves",
    "Data table",
])

with tab1:
    force_data = curve.melt(
        id_vars="angle_deg",
        value_vars=["lift_N", "drag_N"],
        var_name="Force",
        value_name="Force (N)",
    )
    fig = px.line(
        force_data,
        x="angle_deg",
        y="Force (N)",
        color="Force",
        title="Predicted forces vs angle of attack",
        labels={"angle_deg": "Angle of attack (°)"},
    )
    fig.add_vline(
        x=stall_angle,
        line_dash="dash",
        annotation_text="Assumed positive stall angle",
    )
    fig.add_vline(
        x=-stall_angle,
        line_dash="dash",
        annotation_text="Assumed negative stall angle",
    )
    st.plotly_chart(fig, use_container_width=True)

with tab2:
    coefficient_data = curve.melt(
        id_vars="angle_deg",
        value_vars=["CL", "CD"],
        var_name="Coefficient",
        value_name="Coefficient value",
    )
    fig2 = px.line(
        coefficient_data,
        x="angle_deg",
        y="Coefficient value",
        color="Coefficient",
        title="Lift and drag coefficients vs angle of attack",
        labels={"angle_deg": "Angle of attack (°)"},
    )
    st.plotly_chart(fig2, use_container_width=True)

with tab3:
    st.dataframe(curve.round(5), use_container_width=True)

# ---------------- CURRENT TEST TABLE ----------------
st.markdown("### Current test details")

summary = pd.DataFrame([
    {"Parameter": "Angle of attack", "Value": angle, "Unit": "degrees"},
    {"Parameter": "Air density", "Value": rho, "Unit": "kg/m³"},
    {"Parameter": "Air velocity", "Value": velocity, "Unit": "m/s"},
    {"Parameter": "Wing reference area", "Value": wing_area, "Unit": "m²"},
    {"Parameter": "Lift", "Value": current["lift_N"], "Unit": "N"},
    {"Parameter": "Drag", "Value": current["drag_N"], "Unit": "N"},
    {"Parameter": "Lift coefficient", "Value": current["CL"], "Unit": "-"},
    {"Parameter": "Drag coefficient", "Value": current["CD"], "Unit": "-"},
    {"Parameter": "Idealized stall speed", "Value": vs, "Unit": "m/s"},
    {"Parameter": "Estimated spar stress", "Value": stress["stress_MPa"], "Unit": "MPa"},
])

st.dataframe(summary, use_container_width=True)

# ---------------- EXPORT ----------------
st.markdown("### Export results")

csv_bytes = summary.to_csv(index=False).encode("utf-8")
curve_bytes = curve.to_csv(index=False).encode("utf-8")

left, right = st.columns(2)

left.download_button(
    "Download current test (CSV)",
    data=csv_bytes,
    file_name="aerolab_test_summary.csv",
    mime="text/csv",
)

right.download_button(
    "Download angle sweep (CSV)",
    data=curve_bytes,
    file_name="aerolab_angle_sweep.csv",
    mime="text/csv",
)

st.markdown("---")
st.caption(
    "AeroLab is a student prototype. Verify all formulas, "
    "reference areas, coefficients, and physical measurements "
    "before drawing real engineering conclusions."
)
